const tires = [
  {
    codigo: "ENERGY ADR3",
    table: {
      size: "295/80R22.5",
      pr: 18,
      loadRange: "J",
      style: "TL",
      loadIndex: "154/151",
      traedDepth: { nds: 26.5, mm: 21.0 },
      maxSpeed: 75,
      speedRating: "L/M",
      overallDiameter: { in: 41.1, mm: 1044 },
      overallWith: { in: 11.7, mm: 298 },
      standarRim: 9.0,
      maxTireLoadSingle: {
        lbs: 8270,
        psi: 130,
        kg: 3750,
        kpa: 900,
      },
      maxTireLoadDual: {
        lbs: 7610,
        psi: 130,
        kg: 3450,
        kpa: 900,
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
  {
    codigo: "",
    table: {
      size: "",
      pr: "",
      loadRange: "",
      style: "",
      loadIndex: "",
      traedDepth: { nds: "", mm: "" },
      maxSpeed: "",
      speedRating: "",
      overallDiameter: "",
      overallWith: "",
      standarRim: "",
      maxTireLoadSingle: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
      maxTireLoadDual: {
        lbs: "",
        psi: "",
        kg: "",
        kpa: "",
      },
    },
  },
];
